//creo las actiontypes
export const ActionTypes = {
    GET_DOGS : 'GET_DOGS',
    GET_TEMPERAMENTS : 'GET_TEMPERAMENTS',
    GET_NAMES_ON_SEARCH: 'GET_NAMES_ON_SEARCH',
    POST_DOG: 'POST_DOG',
    FILTER_BY_TEMPERAMENT : 'FILTER_BY_TEMPERAMENT',
    FILTER_BY_SOURCE: 'FILTER_BY_SOURCE',
    ORDER_BY_NAME: 'ORDER_BY_NAME',
    ORDER_BY_WEIGHT: 'ORDER_BY_WEIGHT',
    GET_DETAIL: 'GET_DETAIL'
}